[package]
name = "sushi-error"
version = "0.1.0"
edition = "2021"

[dependencies]
sushi-lexer = { path = "../sushi-lexer" }
sushi-common = { path = "../sushi-common" }
lalrpop-util = { version = "0.19.8", default-features = false }
ariadne = "0.1.5"
