[package]
name = "sushi-interpreter"
version = "0.1.0"
edition = "2021"

[dependencies]
sushi-parser = { path = "../sushi-parser" }
sushi-lexer = { path = "../sushi-lexer" }
sushi-ast = { path = "../sushi-ast" }
sushi-common = { path = "../sushi-common" }
sushi-error = { path = "../sushi-error" }
